version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - spark
    ports:
      - 5432:5432

  database-service:
    build:
      context: ./database-service
      dockerfile: dockerfile
      target: production
    networks:
      - spark
    command: sh -c "./command.sh"
    restart: always
    env_file:
      - ./database-service/.env.docker
    depends_on:
      - db

volumes:
  data:

networks:
  spark:
    external: false
