version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  ai:
    build: ./AI
    restart: always
    ports:
      - 5001:5000

volumes:
  data:
